### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by rsmitty** [phoenixnap/k8s-cloud-provider-bmc#1]
Hey @deitch hope you're well. Can you go through the process of cutting a new release of this repo? Looks like a new one never got cut when the repo was moved.

Thanks!

**Comment by deitch** [comment]
Hi @rsmitty; anyone with write rights (say that 5 times quickly) should be able to add a semver tag `vX.Y.Z`, which will cut a tagged version on that commit to the hub.

**Comment by marcolenzo-phoenixnap** [comment]
This should be sorted. Let me know if you need anything else.

https://github.com/phoenixnap/k8s-cloud-provider-bmc/releases/tag/v1.0.0

**Comment by rsmitty** [comment]
@marcolenzo-phoenixnap I still don't think the actual image is public unfortunately. Getting a denied error when trying to do a docker pull of ghcr.io/phoenixnap/k8s-cloud-provider-bmc:v1.0.0

**Comment by pajuga** [comment]
@rsmitty are you still having issues to pull docker image. The way it works is 
docker pull ghcr.io/phoenixnap/k8s-cloud-provider-bmc:1.0.0 
or docker pull ghcr.io/phoenixnap/k8s-cloud-provider-bmc
